### ISSUE TITLE
Notice exploding classes array, drupal 8.1 already send array

### ISSUE THREAD

**Issue by mgomma** [yannickoo/menu_link_attributes#10]
Warning: explode() expects parameter 2 to be string, array given in menu_link_attributes_get_attributes() (line 149 of modules/menu_link_attributes/menu_link_attributes.module). 

Solution:
Check if it was not array before continue, Here the diff line 148

`-    if (isset($attributes['class'])) {
-    if (isset($attributes['class']) && !is_array($attributes['class'])) {`

**Comment by yannickoo** [comment]
Thank you for reporting this issue @mgomma, I've fixed this ebe36a0e859b184d5799a818a196e2ded7df9483 😇

**Comment by mgomma** [comment]
You are welcome, I like contribute to drupal projects
