### ISSUE TITLE
Option to not print empty attributes

### ISSUE THREAD

**Issue by Soundvessel** [yannickoo/menu_link_attributes#11]
In your example a select drop-down is provided for <code>target</code> but if nothing is selected it prints the attribute anyways. Because some attributes are allowed exist without values maybe we can add a configurable option to the yaml config to not print the attribute when it doesn't have any values?

**Comment by santas156** [comment]
Any attribute that has no value is printed (target, id, class, etc.). I think we need one **if** in code to find out empty attribute is or not and print attribute with value only.

**Comment by yannickoo** [comment]
I have added a check for the string length in 2138381f0a64d025ac55a131fe54cd18ee3f46d9 so we can get rid of empty attributes 🎉

**Comment by yannickoo** [comment]
_This issue has been moved to Drupal.org – [#3199781](https://www.drupal.org/project/menu_link_attributes/issues/3199781)_
