### ISSUE TITLE
Default value options for target

### ISSUE THREAD

**Issue by LaravZ** [yannickoo/menu_link_attributes#12]
Hi,

Not setting the Target attribute to a value leads to a w3c html validation error: _Bad value  for attribute target on element a: Browsing context name must be at least one character long._
If possible, I would like to suggest adding a default option to the target attribute in the menu_link_attributes.config.yml file and perhaps even setting this value to _self to avoid this validation error.

Is this something that would be doable for the menu link attributes module, or is this module going to fully merge into the menu attributes module?

Sincerely,
LaravZ

PS. My bad, this seems to be a duplicate of issue #11.

**Comment by yannickoo** [comment]
Hey @LaravZ, #11 is closed now because I've removed the empty attributes in 2138381f0a64d025ac55a131fe54cd18ee3f46d9. Feel free to update :)
