### ISSUE TITLE
mb_strlen warnings

### ISSUE THREAD

**Issue by kuebel** [yannickoo/menu_link_attributes#13]
Hi!

function menu_link_attributes_get_attributes produces mb_strlen warnings

mb_strlen() expects parameter 1 to be string, array given in

that's because the attributes['class'] will now, after your last change, always be an array.

The corrected version could be:

```
  // Remove empty attributes by checking their string length.
  foreach ($attributes as &$attribute) {
    if (!is_array($attribute) && Unicode::strlen($attribute) === 0) {
      unset($attribute);
    }
  }
```

**Comment by yannickoo** [comment]
Oh, thank you @kuebel for reporting and thank you @abstractpenguin for fixing this issue :)
