### ISSUE TITLE
Enable attribute form also in views

### ISSUE THREAD

**Issue by pixelmord** [yannickoo/menu_link_attributes#16]
At the moment the attributes cannot be set for menu links configured from within the views interface

**Comment by josuevalrob** [comment]
how is this going??

**Comment by stankut** [comment]
+1 interested

**Comment by yannickoo** [comment]
_This issue has been moved to Drupal.org – [#3199786](https://www.drupal.org/project/menu_link_attributes/issues/3199786)_
