### ISSUE TITLE
Empty attributes arent properly removed (e.g. empty target attribute)

### ISSUE THREAD

**Issue by rgpublic** [yannickoo/menu_link_attributes#20]
The problem is in line #173 of menu_link_attributes.module:

```
     // Remove empty attributes by checking their string length.
      foreach ($attributes as &$attribute) {
        if (!is_array($attribute) && Unicode::strlen($attribute) === 0) {
          unset($attribute);
        }
      }
```

Unset on a reference doesnt work that way. Only the reference is "unreferenced" in this case. The original value stays the same. You need to unset the key: 

```
     // Remove empty attributes by checking their string length.
      foreach ($attributes as $key=>$attribute) {
        if (!is_array($attribute) && Unicode::strlen($attribute) === 0) {
          unset($attributes[$key]);
        }
      }
```

**Comment by kevinquillen** [comment]
This still doesn't quite work - empty attributes are still being output in the source.

edit: the code itself works, but the page still outputs the attributes in the HTML source.

**Comment by benjaminmerkley** [comment]
Changed some code here and that helped me
--- a/menu_attributes.module
+++ b/menu_attributes.module
@@ -83,7 +83,7 @@ function menu_attributes_menu_attribute_info() {
     'form' => [
       '#type' => 'select',
       '#options' => [
-        '' => t('None (i.e. same window)'),
+        '_self' => t('None (i.e. same window)'),
         '_blank' => t('New window (_blank)'),
         '_top' => t('Top window (_top)'),
         '_self' => t('Same window (_self)'),

**Comment by yannickoo** [comment]
Empty attributes are being filtered after saving menu link now so there is no need to filter them somewhere else :)
