### ISSUE TITLE
Added Capability for Additional Field Types, ex: textarea

### ISSUE THREAD

**Issue by andrewleegoss** [yannickoo/menu_link_attributes#21]
Added Capability for Additional Field Types, ex: textarea

Link to bitbucket patch: https://bitbucket.org/!api/2.0/snippets/texascreative/yoeRr/1be075a526b0e53cae6956b444af8c3091938649/files/textarea_for_type-1-1.patch

**Comment by kevinquillen** [comment]
Yes, please. Some of the attributes I just want to trigger as a checkbox for end users. This patch makes it happen.

**Comment by yannickoo** [comment]
Thank you for this idea, tested it with a textarea and a checkbox and it just works 💪
