### ISSUE TITLE
How can I place attributes to menu

### ISSUE THREAD

**Issue by ghost** [yannickoo/menu_link_attributes#23]
I want to have icons to my menu. After viewing this module I installed it and added a class to my link.
Now how can I place the attribute to my menu in the menu.html.twig page?

**Comment by tuthanh82** [comment]
When you add a class to a menu item, you can style it with CSS to put your own icon there.

This is a CSS issue, I believe, not a module issue.

**Comment by MANTENN** [comment]
How do I use the attributes in the file in main--menu.html.twig?

**Comment by yannickoo** [comment]
We will provide more documentation how to access attributes programatically :)
