### ISSUE TITLE
loadEntityByUuid return null in some cases

### ISSUE THREAD

**Issue by abuzakham** [yannickoo/menu_link_attributes#26]
Hello, After install module I got this error
`Fatal error: Call to a member function first() on null in /.../menu_link_attributes/menu_link_attributes.module on line 162`

After debugging I notice something wrong in uuid "fded6395-d5f8-48d6-b708-cefebe737654:4", 
I think the best and safe solution is add strstr to trim extra text if exist like 

`$uuid = strstr($uuid, ':', true);` I will create pull request fir this solution

Regards.

**Comment by yannickoo** [comment]
The extra code that included the `loadEntityByUuid` has been removed in #30. I have committed 4d9d2ef8c79aee9efc83edfcdd46239a4d8add2a which checks for `$menu_link->link` just to make sure.
