### ISSUE TITLE
Add class to list item instead / in addition to link

### ISSUE THREAD

**Issue by vegardjo** [yannickoo/menu_link_attributes#28]
Hi, I would very much like an option to add the class to the menu list item (`<li>`), not the menu link (`<a>`) itself. 

In my case I have a nested menu where I would like to style the child li items based on the class of the parent, but this is not possible when the class is added to the link as the structure is:

- li
  - a
  - ul 
    - li 
    - a

In general adding it to the highest level makes styling a lot easier. 

I realise this cannot be done for options like for instance target, and also that you can't break the current functionality, but maybe something like a checkbox "add to list item" for the class option could be feasible?

**Comment by jfbcofomo** [comment]
I second that request

**Comment by yannickoo** [comment]
Hey! You can try the latest version and create a new attribute starting with `container_` e.g. `container_class`. It will appear in `Container attributes` automatically 😇 

## Screenshot

<img width="570" alt="screen shot 2017-10-04 at 00 21 26" src="https://user-images.githubusercontent.com/1086961/31151988-4ddb5d84-a89a-11e7-8c81-e833635bf9b7.png">
