### ISSUE TITLE
Cannot set attributes on <nolink> menu links

### ISSUE THREAD

**Issue by zessx** [yannickoo/menu_link_attributes#29]
Drupal 8 allows you to create empty links, without any page behind.  
You simply have to leave the link field empty.

But whenever you edit this menu link, menu_link_attributes will raise these errors:

> Notice: Trying to get property of non-object in menu_link_attributes_menu_link_content_form_submit() (line 99 of modules/contrib/menu_link_attributes/menu_link_attributes.module).

> Warning: array_merge(): Argument #1 is not an array in menu_link_attributes_menu_link_content_form_submit() (line 100 of modules/contrib/menu_link_attributes/menu_link_attributes.module).

> Warning: Creating default object from empty value in menu_link_attributes_menu_link_content_form_submit() (line 100 of modules/contrib/menu_link_attributes/menu_link_attributes.module).

Related lines:

    $menu_link_options = $menu_link->link->first()->options;
    $menu_link->link->first()->options = array_merge($menu_link_options, $options);
    $menu_link->save();

I currently avoid errors with this code:

    $link = $menu_link->link->first();
    if ($link) {
      $menu_link_options = $link->options;
      $link->options = array_merge($menu_link_options, $options);
      $menu_link->save();
    }

**But this does not fix the problem**. We need to find a way to add attributes on empty links.  
And if this is not possible, the attributes block should at least be disabled for these links.

**Comment by diamondsea** [comment]
For the link, use:
`route:<nolink>`
It will let you edit the menu item and you can add attributes.

**Comment by yannickoo** [comment]
I have just tested this module with `route:<nolink>` and it works fine, closing this one :)
