### ISSUE TITLE
Attributes not working after DB restore

### ISSUE THREAD

**Issue by donhollen** [yannickoo/menu_link_attributes#37]
Had to restore a db backup.

The menu items still have their settings, but do not trigger new window UNLESS i open that menu link, do nothing, and save it.

I've cleared all caches, and even looked at the db. 
I see the link attributes in the db table menu_link_content_data , and two links with identical link_options behave differently.

Link One : Opens in new tab (because I opened the link and saved)
Link 2: Does not open in new tab. (did not alter it, but you can see the _blank in the db)

**Comment by aaron-capellic** [comment]
I've noticed the same behavior with link classes after drush config-import.

**Comment by yannickoo** [comment]
Feel free to [create](https://www.drupal.org/node/add/project-issue/menu_link_attributes) a new issue on drupal.org if you are still experiencing this issue.
