### ISSUE TITLE
Normalize menu link attributes options property

### ISSUE THREAD

**Issue by Thommusa** [yannickoo/menu_link_attributes#44]
Hi
here the issue on drupal.org, let me know if it's not clear. https://www.drupal.org/project/default_content_deploy/issues/2926800

**Comment by Flodevelop** [comment]
I need this functionnality too.
Subscribe.

**Comment by yannickoo** [comment]
It seems like there is a core issue for it: https://www.drupal.org/project/drupal/issues/2895532 so we could close this one.
