### ISSUE TITLE
Provide a way of adding attributes to module-provided links

### ISSUE THREAD

**Issue by iamsophiesk** [yannickoo/menu_link_attributes#45]
We've noticed that there is no way to add an attribute to a link that a module has provided. For example, if you create a custom admin link in a module and add it to a user-facing menu where all other menu items have an icon, there's no way to add an icon to the link in the menu structure.

I can see why - the main form alter is on the base content link entity form, and links that are created in a module are not content link entites. 

We tried to get around this quickly by adding an extra form alter to target the menu_link_edit form, but of course the code fails because there is no `$form_state->getFormObject()->getEntity()`. 

Then there would be no way to save that information because there is no menu link entity. 

It would be good if there were a way to add attributes to module-provided links. My team's happy to help out with patches and testing where possible, after the Christmas break. Has there been any kind of initiative to work on this, or any half-worked code? Any help is appreciated.

Thank you!

**Comment by cdog** [comment]
Hello,

I need this too, for links defined in `mymodule.links.menu.yml`. Also would be great to be able to replace the link title. Is this something that could be implemented/extended with this module? See an example below.
```
mymodule.order:
  title: 'Made-to-order'
  parent: ''
  menu_name: main
  route_name: mymodule.order
  weight: 10
```
The above configuration produces the following markup in the main navigation.
```
<a href="/order" data-drupal-link-system-path="order">Made-to-order</a>
```
Would like to alter it to render the following markup (class attribute and custom html inside the `<a>` tag only in front-end).
```
<a class="add-element" href="/order" data-drupal-link-system-path="order">
  <span class="my-custom-icon"></span>
</a>
```
Thanks for the great module, appreciate your work!

**Comment by lukasvs** [comment]
Any progress here please!

**Comment by mlncn** [comment]
The [Link Attributes widget](https://www.drupal.org/project/link_attributes/issues/2781195 ) module said explicitly it won't support this.

Definitely curious if there's anything about this module (Menu Link Attributes) that makes this more possible or if this module more amenable to bolting it on.

Hold on, we have a core issue about changing titles of code-provided menu that might shed some light on this...

Allow override the menu link titles at core.menu.static_menu_link_overrides.yml 
https://www.drupal.org/node/2916639

**Comment by mlncn** [comment]
(Oh wanted to mention that the recommended workaround for link attributes is to disable the code-provided menu, and create a custom menu item, but that is deeply unsatisfying when trying to get everything into configuration, which is like the whole game for sustainable development and necessary for building distributions like [Drutopia](https://drutopia.org/ ).)

**Comment by mlncn** [comment]
Related: https://stackoverflow.com/questions/46114027/add-menu-class-in-drupal8

**Comment by yannickoo** [comment]
Closing this one, please [create](https://www.drupal.org/node/add/project-issue/menu_link_attributes) a new issue if this is still needed.
