### ISSUE TITLE
Adding file upload field attribute 

### ISSUE THREAD

**Issue by AMarwen** [yannickoo/menu_link_attributes#50]
I'm using the D8 Menu Link Attributes module to add an attribute to a menu item using the yml configuration offered by the module ex:

attributes:
  title:
    label: 'Tooltip text'
    type: file
The code Above works fine, but the file is always downloaded to a temporary location, I have tried to set upload_location key but it seems not working :

attributes:
  image2:
    label: Image2
    type: managed_file
    upload_location: 'public://images/'

**Comment by yannickoo** [comment]
_This issue has been moved to Drupal.org – [#3199793](https://www.drupal.org/project/menu_link_attributes/issues/3199793)_
