### ISSUE TITLE
Container attributes only work with top-level menu items

### ISSUE THREAD

**Issue by jigarius** [yannickoo/menu_link_attributes#53]
## Problem

* Configure a 3 level menu with each menu set to "expanded"
* Place a block to display the entire menu tree
* Add a container attribute to the 3rd level item

You will see that the 3rd level item doesn't get the container attributes.

**Comment by jigarius** [comment]
I did some debugging and found that the `hook_preprocess_menu()` function is only triggered for the top level items.

**Comment by jigarius** [comment]
I fixed this by adding the following code to my `menu.html.twig` override:

```twig
{# See: https://github.com/yannickoo/menu_link_attributes/issues/53 #}
{# Since attributes are not being applied to LI, we add them in Twig #}
{% set li_attributes = item.attributes %}
{% if item.original_link.options.container_attributes %}
  {% for attr_name, attr_value in item.original_link.options.container_attributes %}
      {% if attr_name == 'class' %}
        {% set li_attributes = li_attributes.addClass(attr_value) %}
      {% else %}
        {% set li_attributes = li_attributes.setAttribute(attr_name, attr_value) %}
      {% endif %}
  {% endfor %}
{% endif %}
```

I copied the core `menu.html.twig` for this, but the concept remains the same, no matter what template you override.

I'll stick to my twig approach until I hear back from the community about this (: Thanks!

**Comment by rruprai** [comment]
@jigarius Have you tried the following in your `mytheme_preprocess_menu()`

```
function mytheme_preprocess_menu(&$variables, $hook) {
  if ($hook == 'menu__main') { 
    $items = $variables['items'];
    foreach ($items as $key => $item) {
        // Add active link.
        $variables['items'][$key]['attributes']['class'] = 'someClass';
    }
  }
}
```

**Comment by jigarius** [comment]
Thanks for your comment. I could have done it there as well. But what I mean to say is that the module is supposed to do that for me, isn't it?

**Comment by rruprai** [comment]
That sound like a feature request and here is what I found in the Pull Requests. Can you check if this would be helpful?

[Support container attributes for nested menus](https://github.com/yannickoo/menu_link_attributes/pull/40)

I found this [patch](https://patch-diff.githubusercontent.com/raw/yannickoo/menu_link_attributes/pull/40.patch)

**Comment by jigarius** [comment]
Thanks! Seems to be a meaningful patch. I will give it a try.

For now, I'm closing this ticket as a duplicate of [support container attributes for nested menus](https://github.com/yannickoo/menu_link_attributes/pull/40).
