### ISSUE TITLE
On saving attributes, other attributes are overwritten

### ISSUE THREAD

**Issue by sjerdo** [yannickoo/menu_link_attributes#55]
Hi,

I am using module Micon and Menu Link Attributes. On saving a menu link with a Micon icon and additional custom classes, the 'data-icon' is not Micon saved.

In `menu_link_attributes_menu_link_content_form_submit` [line 145](https://github.com/yannickoo/menu_link_attributes/blob/8.x-1.x/menu_link_attributes.module#L145) the `$menu_link_options` and `$menu_link_attributes` are merged. 

Eg.
```
$menu_link_options = ['attributes' => ['data-icon' => 'icon']];
$menu_link_attributes = ['attributes' => ['class' => 'ico--d-none ico--d-lg ico--s-large ico-l--d-lg-none']];
```

`array_merge()` of these two results in an array equal to `$menu_link_attributes`
I suggest replacing this with `array_merge_recursive()`.

You can test the results at 3v4l.org: https://3v4l.org/ACQmG

**Comment by yannickoo** [comment]
I have merged the PR so we can close this one - thanks!
