### ISSUE TITLE
download attribute

### ISSUE THREAD

**Issue by d0t15t** [yannickoo/menu_link_attributes#57]
Hi,
I'd like to add the 'download' attribute to a link. The attribute doesn't have a value, but looks like this for example: `<a href="doc.pdf" download>Link</a>`
I've found the editor at /admin/config/menu_link_attributes/config, but haven't had any luck setting this up.

**Comment by yannickoo** [comment]
_This issue has been moved to Drupal.org – [#3199792](https://www.drupal.org/project/menu_link_attributes/issues/3199792)_
