### ISSUE TITLE
class not being added if the element already had one

### ISSUE THREAD

**Issue by isaraldi** [yannickoo/menu_link_attributes#59]
Currently we are using the beta3 version of the module, but we've updated it and some of menu items stopped working.
I've noticed this happened only for items that already had one class (that's no the one we've set on the menu link attribute).
But since it was working before the update, we compared the revisions and found out that on menu_link_attributes_preprocess_menu there wasn't any check for it anymore. 
So, based on the beta3 revision, I've created a patch for it and now it's working properly.

[menu_link_attributes_class_not_working.patch.txt](https://github.com/yannickoo/menu_link_attributes/files/2415463/menu_link_attributes_class_not_working.patch.txt)

Hope it helps someone else.

**Comment by JoeKersey** [comment]
Thanks for this patch, it's working well for me!

**Comment by yannickoo** [comment]
Please [create](https://www.drupal.org/node/add/project-issue/menu_link_attributes) a new issue if you are still experiencing this behavior.
