### ISSUE TITLE
render attribute in menu.html.twig

### ISSUE THREAD

**Issue by ymdahi** [yannickoo/menu_link_attributes#62]
Hi new to d8, is there a way to print the attributes created with this modules in menu.html.twig?

For example, I have an attribute like this:
```
  material-icon:
    label: 'Material Icon'
    description: ''
```

When this field is provided, the menu link is rendered like this:
```
<a href="/" material-icon="home" data-drupal-link-system-path="<front>" class="is-active">Home</a>
```

I would like to do something like this in my template:
```
{% if item.attributes.material_icon is defined %}
          <i class="material-icons">{{ item.material_icon }}</i>
{% endif %}
```

How do I get something like this into my template? So far, I cannot get that `<i>` tag to render in menu.html.twig. What is the best way to use attributes created with this module?

Thanks in advance for your help and an awesome module :)

**Comment by tarazingo** [comment]
Good case, I am also interested in this. @ymdahi do you have any results?

**Comment by tarazingo** [comment]
@ymdahi , you can use this 
```
        {% if item.url.getOption('attributes').icon is not null %}
          // Do something
        {% endif %}
```

**Comment by yannickoo** [comment]
Feel free to [create](https://www.drupal.org/project/menu_link_attributes) a new issue in case there are any questions left :)
