### ISSUE TITLE
Error when giving attribut

### ISSUE THREAD

**Issue by seyfcom** [yannickoo/menu_link_attributes#65]
I have a all list of error when I triy to give an attribut.
`Notice: Array to string conversion in Drupal\bootstrap\Utility\Attributes->addClass() (line 29 of themes\contrib\bootstrap\src\Utility\Attributes.php).`

`Notice: Array to string conversion in Drupal\bootstrap\Utility\Attributes->getClasses() (line 59 of themes\contrib\bootstrap\src\Utility\Attributes.php).`

`Notice: Array to string conversion in Drupal\bootstrap\Utility\Attributes->addClass() (line 29 of themes\contrib\bootstrap\src\Utility\Attributes.php).`

`Warning: explode() expects parameter 2 to be string, array given in twig_split_filter() (line 770 of vendor\twig\twig\lib\Twig\Extension\Core.php).`

`Notice: Array to string conversion in Drupal\Core\Template\AttributeArray->__toString() (line 73 of core\lib\Drupal\Core\Template\AttributeArray.php).`

`Notice: Array to string conversion in Drupal\Core\Template\AttributeArray->__toString() (line 74 of core\lib\Drupal\Core\Template\AttributeArray.php).`

I tried to apply your Patch #60 , no change.

If i leave the attribut blank, it's ok.
But I need a class on the LI element. I did exactly like your example, 
attributes:
  container_class:
    label: 'Container class'
    description: 'Enter a class for the wrapping <code>li</code> element.'

The result is 
`<li class="Array class section_enfant expanded dropdown">`
That Array at the start of the class is an error...

Do you have any idea?

Drupal 8.6.5 on XAMP, PHP7.2

**Comment by yannickoo** [comment]
_This issue has been moved to Drupal.org – [#3199777](https://www.drupal.org/project/menu_link_attributes/issues/3199777)_
