### ISSUE TITLE
Can not add attribute with value of 0

### ISSUE THREAD

**Issue by vkechagias** [yannickoo/menu_link_attributes#68]
I am trying to add the tabindex="0" attribute to a menu item.

While this works correctly for values other than 0 (e.g -1) if I enter 0 then the attribute is not added at all.

I have also tried to use 0 as a class and this also does not get added.

It seems that 0 is evaluated as null somewhere and therefore no attribute is added.

**Comment by PaulDinelle** [comment]
**Edit:** Added a patch file for those who want it while this gets reviewed and added.
[68-2--menu_link_attributes--fix-zeroes-not-appearing-on-edit.txt](https://github.com/yannickoo/menu_link_attributes/files/4663859/68-2--menu_link_attributes--fix-zeroes-not-appearing-on-edit.txt)

This was a REALLY tricky one.

**Test/scenario:**
- Added a new attribute called "tabIndex" as an open textfield.
- On a menu item, added the value "0" to the tabIndex attribute.
- Save menu item, then edit again
- **Expected result:** It shows "0" (the value I set earlier).
- **Actual result:** It shows an empty string.

**Problem:**
There is an undocumented bug where `#default_value` will accept an array for textfield `#type`. However, it seems if empty string equivalents are passed as part of the array, they are filtered out (ex. `"0"` attribute values will not appear in the textfield on subsequent edits). This was discovered when trying to add `tabindex=0` attributes, the text would be stripped out upon re-editing the menu item.

**Solution:**
Imploding the array manually into a string when operating on textfields seems to do the trick.

In `menu_link_attributes.module` in the `menu_link_attributes_form_menu_link_content_form_alter` function, just before setting the form API array for `$form['options']['attributes'][$attribute]` (around `line 89`) add the following (to massage the default value ourselves):
```
    // Problem: There is an undocumented bug where #default_value will accept an array for textfield #type.
    // However, it seems if empty string equivalents are passed as part of the array, they are filtered out
    // (ex. "0" attribute values will not appear in the textfield on subsequent edits). This was discovered
    // when trying to add tabindex=0 attributes, the text would be stripped out upon re-editing the menu item.
    // Solution: Imploding the array manually into a string when operating on textfields seems to do the trick.
    $default_value = isset($menu_link_options[$attributes_key][$attribute_formatted]) ? $menu_link_options[$attributes_key][$attribute_formatted] : '';
    if ($type == 'textfield' && is_array($default_value)) {
      $default_value = implode(' ', $default_value);
    }
```

and then below that, replace the `#default_value` value with:
```
    $form['options']['attributes'][$attribute] = [
      '#type' => $type,
      '#title' => $info['label'],
      '#description' => $info['description'],
      '#default_value' => $default_value,
    ];
```

Unfortunately I'm not set up to create patches, but hopefully someone can add this in.

**Comment by yannickoo** [comment]
_This issue has been moved to Drupal.org – [#3199781](https://www.drupal.org/project/menu_link_attributes/issues/3199781)_
