### ISSUE TITLE
Below items

### ISSUE THREAD

**Issue by progzy** [yannickoo/menu_link_attributes#7]
Hello,

Thanks for your module.

I have noticed that below items are not affected by the module. 

This could be fixed by calling a recursive function that sets attributes for one item inside the preprocess menu hook function inside the foreach loop.

Thank you.

**Comment by axe312ger** [comment]
@yannickoo I think did that before for my menu module:
https://github.com/axe312ger/expanded_menu_block/blob/8.x-1.x/src/Plugin/Block/ExpandedMenuBlock.php#L78
https://github.com/axe312ger/expanded_menu_block/blob/8.x-1.x/src/ExpandedTreeManipulators.php

**Comment by zuuperman** [comment]
This pull request fixes this issue: https://github.com/yannickoo/menu_link_attributes/pull/5

**Comment by yannickoo** [comment]
Yeah! Thank you @zuuperman :)
