### ISSUE TITLE
Dependency namespacing in .info.yml file

### ISSUE THREAD

**Issue by vernitgupta** [yannickoo/menu_link_attributes#72]
According to Drupal standards, modules should include dependencies in the .info.yml file. Dependencies should be namespaced in the format {project}:{module}, where {project} is the project name as it appears in the Drupal.org URL (e.g. drupal.org/project/views) and {module} is the module's machine name.
https://www.drupal.org/docs/8/creating-custom-modules/let-drupal-8-know-about-your-module-with-an-infoyml-file Patch to follow, thanks!
#73 Refer the pull request for same.

**Comment by yannickoo** [comment]
PR has been merged, thanks :)
