### ISSUE TITLE
Active class overrides custom one

### ISSUE THREAD

**Issue by kdarko91** [yannickoo/menu_link_attributes#75]
After updating core to 8.8.1, active class for menu items override custom class defined for that menu item.
To reproduce this, do the following:

- Create or edit menu item and set class attribute
- Go to linked page
- Only "is-active" class is present on anchor tag

**Comment by albertski** [comment]
I'm having the same issue. I looked over the code and can't seem to figure out how this is not working. I wonder if it is something on Drupal's end that is causing this. I am on Drupal 8.8.6.

**Comment by joannamay** [comment]
having the same issue on 8.8

**Comment by GTR18** [comment]
In my case, the menu_token module was overriding the value in the MenuLinkTreeMenuToken.php Line 47.

**Comment by yannickoo** [comment]
_This issue has been moved to Drupal.org – [#3199777](https://www.drupal.org/project/menu_link_attributes/issues/3199777)_
