### ISSUE TITLE
Missing options property notice when link empty

### ISSUE THREAD

**Issue by jroberson108** [yannickoo/menu_link_attributes#76]
A PHP notice is logged if the menu item has an empty link field value. This is possible if you have a parent menu item w/o a link and children menu items w/ links. I'm using **Drupal 8.8.1** and **PHP 7.3**.

**PHP Notice:**
```
Notice: Trying to get property 'options' of non-object in menu_link_attributes_menu_link_content_form_submit() (line 126 of /modules/contrib/menu_link_attributes/menu_link_attributes.module)

#0 /core/includes/bootstrap.inc(596): _drupal_error_handler_real(8, 'Trying to get p...', '...', 126, Array)

#1 /modules/contrib/menu_link_attributes/menu_link_attributes.module(126): _drupal_error_handler(8, 'Trying to get p...', '...', 126, Array)

#2 [internal function]: menu_link_attributes_menu_link_content_form_submit(Array, Object(Drupal\Core\Form\FormState))
...
```

In looking at the issue (line 126 of menu_link_attributes.module), I found that the **$menu_link->link** object is not empty when the link value is empty. **$menu_link->link->first()** gives an empty value when no link value exists, which causes **$menu_link->link->first()->options** to produce a notice. The fix is on line 121 where the "empty" check is done.

**Patch file code:**
```
diff --git a/menu_link_attributes.module b/menu_link_attributes.module
index 6f194e3..30dc1e4 100644
--- a/menu_link_attributes.module
+++ b/menu_link_attributes.module
@@ -118,7 +118,7 @@ function menu_link_attributes_menu_link_content_form_submit($form, FormStateInte
   $form_object = $form_state->getFormObject();
   $menu_link = $form_object->getEntity();
 
-  if (!$menu_link->link) {
+  if ($menu_link->link->isEmpty()) {
     return;
   }
```

**Comment by yannickoo** [comment]
_This issue has been moved to Drupal.org – [#3199782](https://www.drupal.org/project/menu_link_attributes/issues/3199782)_
