### ISSUE TITLE
Removing the depricated drupal_set_message()

### ISSUE THREAD

**Issue by nitesh624** [yannickoo/menu_link_attributes#77]
In src/Form/ConfigForm.php there is depricated function drupal_set_message() has used which is depricated in  drupal 9

**Comment by nitesh624** [comment]
diff --git a/src/Form/ConfigForm.php b/src/Form/ConfigForm.php
index 0d02636..2e29a58 100644
--- a/src/Form/ConfigForm.php
+++ b/src/Form/ConfigForm.php
@@ -6,6 +6,7 @@ use Drupal\Core\Form\ConfigFormBase;
 use Drupal\Core\Form\FormStateInterface;
 use Drupal\Component\Serialization\Exception\InvalidDataTypeException;
 use Drupal\Component\Serialization\Yaml;
+use Drupal\Core\Messenger\MessengerInterface;
 
 /**
  * Class ConfigForm.
@@ -43,8 +44,7 @@ class ConfigForm extends ConfigFormBase {
       $message = $this->t('It is recommended to install the <a href="@yaml-editor">YAML Editor</a> module for easier editing.', [
         '@yaml-editor' => 'https://www.drupal.org/project/yaml_editor',
       ]);
-
-      drupal_set_message($message, 'warning');
+      \Drupal::messenger()->addWarning($message);
     }
 
     $form['config'] = array(

**Comment by yannickoo** [comment]
Has been fixed in #66, thanks for reporting :)
