### ISSUE TITLE
Maintainership permissions

### ISSUE THREAD

**Issue by NickDickinsonWilde** [yannickoo/menu_link_attributes#82]
Hey yannickoo.
My team is using this project in Drupal sites that we are pre-looking at/preparing for Drupal 9. It would be great if the D9 pulls could be implemented and a new release made. If you aren't active in this space right now, or are too busy, I'm wondering if I could have maintainership permissions?
Thanks;
Nick

**Comment by heddn** [comment]
:+1: on granting @NickDickinsonWilde this access.

**Comment by lems3** [comment]
We actually just removed this module from a project since there's too many unresolved issues with it. I'd really recommend the current maintainer to add people to the project so it could move forward in the future...

**Comment by yannickoo** [comment]
Hey sorry for the inactivity here in the issue queue. This project is actively maintained again and I'm currently moving the issues to drupal.org since forks can be created there now as well 💪
