### ISSUE TITLE
Update README on how to install

### ISSUE THREAD

**Issue by douggreen** [yannickoo/menu_link_attributes#83]
Please document how to install the dev version from GitHub. The readme says "Install the module the drupal way".

However, this only applies to installing a tagged release on d.o. Because the module is maintained in GitHub, because it has not had a release in several years, and because there is not a dev version on d.o, the standard way to install the Drupal module does not apply. To install the dev version, you need to get it from GitHub with composer.

The only solution I've come up with is below. If there's a better way than below, please document that way instead:

```
"repositories": [
    {
       "type": "package",
        "package": {
            "name": "yannickoo/menu_link_attributes",
           "version": "1.x-dev",
           "type": "drupal-module",
            "dist": {
                "url": "https://codeload.github.com/yannickoo/menu_link_attributes/zip/8.x-1.x",
                "type": "zip"
            }
        }
    }
],
"require": {
    "yannickoo/menu_link_attributes": "1.x-dev"
}
```

**Comment by dpi** [comment]
Try adding the repo to your composer.json, then running `composer update drupal/menu_link_attributes`

```
    "repositories": [
        {
            "type": "git",
            "url": "git@github.com:yannickoo/menu_link_attributes.git"
        },
```

**Comment by douggreen** [comment]
If I do that along with: 
```
"yannickoo/menu_link_attributes": "dev-8.x-1.x",
```
I get "The requested package yannickoo/menu_link_attributes could not be found in any version, there may be a typo in the package name."

**Comment by dpi** [comment]
The package name is `drupal/menu_link_attributes`. You can use `composer require drupal/menu_link_attributes:dev-BRANCHNAME`

**Comment by douggreen** [comment]
doh, sorry yes. While this is the common composer solution, it's not the common Drupal way. It would have helped me if this was documented it in the README.md instead of just saying "Install the module the drupal way". ... but I see where that might be confusing to people too.

Maybe the better solution is to cut more frequent releases ¯\_(ツ)_/¯

**Comment by dpi** [comment]
I think for development its fine to leave undocumented.

Any changes end users require should already be pushed and packaged at d.o. They are not currently so thats unfortunate.

**Comment by dpi** [comment]
@yannickoo could you push 8.x-1.x through to Drupal.org?

**Comment by yannickoo** [comment]
It seems like there was an error in the sync process but this has been fixed now, latest commits are visible again on https://www.drupal.org/node/2578907/commits

@douggreen there is dev version on drupal.org, GitHub and drupal.org are synced so you should be able to use composer to install it.

**Comment by yannickoo** [comment]
Closing this one since there is already a new release on drupal.org.
