### ISSUE TITLE
Drupal 9 compatible release

### ISSUE THREAD

**Issue by jigarius** [yannickoo/menu_link_attributes#86]
I see that the 1.x branch is compatible with Drupal 9. However, a new release needs to be created on Drupal.org so that people can start using it.

Thanks for maintaining the module.

**Comment by JTubex** [comment]
+1

**Comment by jrglasgow** [comment]
+1

**Comment by JTubex** [comment]
This module has a Drupal 9 compatible release since june 29th: https://www.drupal.org/project/menu_link_attributes/releases/8.x-1.1

**Comment by jrglasgow** [comment]
it is interesting that the project page doesn't list it as D9 compatible 
![image](https://user-images.githubusercontent.com/1824713/94951792-25c7db80-04a2-11eb-8fb5-bff67df8af4e.png)
